# Generated by Django 6.0 on 2026-01-13 06:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diveops", "0072_performance_indexes"),
        ("django_parties", "0004_add_lead_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[("android", "Android"), ("ios", "iOS")],
                        help_text="Mobile platform (android or ios)",
                        max_length=10,
                    ),
                ),
                (
                    "version_code",
                    models.PositiveIntegerField(
                        help_text="Numeric version code (e.g., 1, 2, 3). Matches Android versionCode."
                    ),
                ),
                ("version_name", models.CharField(help_text="Display version string (e.g., '1.0.0')", max_length=20)),
                ("download_url", models.URLField(blank=True, help_text="Direct APK/IPA download URL")),
                (
                    "is_force_update",
                    models.BooleanField(
                        default=False, help_text="If True, users on older versions must update before using the app"
                    ),
                ),
                (
                    "min_supported_version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum version_code still allowed to run. Versions below this are blocked.",
                    ),
                ),
                (
                    "release_notes",
                    models.TextField(blank=True, help_text="What's new in this version (shown in update dialog)"),
                ),
                ("released_at", models.DateTimeField(auto_now_add=True, help_text="When this version was released")),
            ],
            options={
                "ordering": ["-version_code"],
                "indexes": [models.Index(fields=["platform", "version_code"], name="diveops_app_platfor_06e67f_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("platform", "version_code"),
                        name="unique_platform_version_active",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LocationSharingPreference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private (No one)"),
                            ("staff", "Staff Only"),
                            ("trip", "Trip Participants"),
                            ("buddies", "Dive Buddies"),
                            ("public", "All Users"),
                        ],
                        default="private",
                        help_text="Default visibility level for location updates",
                        max_length=20,
                    ),
                ),
                (
                    "is_tracking_enabled",
                    models.BooleanField(default=False, help_text="Whether to actively upload location updates"),
                ),
                (
                    "tracking_interval_seconds",
                    models.PositiveIntegerField(default=60, help_text="Minimum seconds between location uploads"),
                ),
                (
                    "always_share_with",
                    models.ManyToManyField(
                        blank=True,
                        help_text="People who can always see this person's location regardless of visibility setting",
                        related_name="always_sees_location_of",
                        to="django_parties.person",
                    ),
                ),
                (
                    "never_share_with",
                    models.ManyToManyField(
                        blank=True,
                        help_text="People blocked from seeing location even if visibility would allow",
                        related_name="never_sees_location_of",
                        to="django_parties.person",
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        help_text="Person these preferences belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_sharing_preference",
                        to="django_parties.person",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["visibility"], name="diveops_loc_visibil_a3e0bf_idx")],
            },
        ),
        migrations.CreateModel(
            name="LocationUpdate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(decimal_places=6, help_text="Latitude coordinate (-90 to 90)", max_digits=9),
                ),
                (
                    "longitude",
                    models.DecimalField(decimal_places=6, help_text="Longitude coordinate (-180 to 180)", max_digits=9),
                ),
                (
                    "accuracy_meters",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="GPS accuracy in meters", max_digits=10, null=True
                    ),
                ),
                (
                    "altitude_meters",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Altitude above sea level in meters",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("gps", "GPS"),
                            ("network", "Network"),
                            ("fused", "Fused (GPS+Network)"),
                            ("manual", "Manual Entry"),
                        ],
                        default="fused",
                        help_text="How location was obtained",
                        max_length=10,
                    ),
                ),
                ("recorded_at", models.DateTimeField(help_text="Device timestamp when location was captured")),
                (
                    "excursion",
                    models.ForeignKey(
                        blank=True,
                        help_text="Active excursion when location was recorded",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="location_updates",
                        to="diveops.excursion",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text="Person whose location was recorded",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_updates",
                        to="django_parties.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(fields=["person", "-recorded_at"], name="diveops_loc_person__c3b9ea_idx"),
                    models.Index(fields=["recorded_at"], name="diveops_loc_recorde_4da27f_idx"),
                    models.Index(fields=["excursion", "recorded_at"], name="diveops_loc_excursi_26abc2_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                        name="location_update_valid_latitude",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                        name="location_update_valid_longitude",
                    ),
                ],
            },
        ),
    ]
